import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen flex items-center justify-center">
        <h1 className="text-3xl font-bold underline">
          Next + Tailwindcss
        </h1>
      </main>
    </div>
  )
}

export default Home
